#ECOAPI-784: Melhorias SDK Node (senior-core-node)
dev-senior-com-br/senior-core-node pull request #38
Opened 2020-08-26 12:55 UTC by wallacetm

2020-08-26 12:56 UTC, wallacetm commented
Foi feito uma quebra de compatibilidade em quase todas as chamadas.

2020-09-01 12:19 UTC, jefersonfrancisco requested changes
https://github.com/dev-senior-com-br/senior-core-node/blob/8fc88c598d8687b4f93b781fa2c1d9f598c75d9d/lib/resources/Authorization.ts#L31

Esta retornando 401 pois está faltando o header authentication.

2020-09-01 13:53 UTC, jefersonfrancisco requested changes
No SDK tem os métodos deleteUser e deleteGroup apontando para as apis da Entity, porém esse serviço não utiliza a EDL para a geração das entidades. É necessário efetuar a chamada dos métodos para  /actions/deleteUser e /actions/removeGroup

2020-09-01 18:07 UTC, jefersonfrancisco approved these changes

2020-09-01 18:12 UTC, merged